#!/bin/bash

# shellcheck disable=SC1091

[ -n "${DEBUG:+1}" ] && set -x

. /etc/s6/s6-init/envs

exec /usr/local/bin/k3s server --tls-san local.k3s --data-dir /opt/quickon/platform --disable-network-policy --disable-helm-controller --disable="servicelb,traefik"
